Reset
BetterACS/brainboost pull request #3
Opened 2024-12-24 14:53 UTC by Endo-Sym

2024-12-24 14:56 UTC, monshinawatra commented
อันนี้ม่อนว่าน่าจะต้องเปลี่ยนชื่อ Pull request ว่า 'Implement Home page & Navigation bar'
แล้วก็รอบหน้าๆ ฝากใส่ใน description มาด้วยว่าแก้อะไรไปบ้าง

2024-12-24 14:58 UTC, monshinawatra commented on README.md
อันนี้ไม่ต้อง Push ขึ้นมานะ ฝากลบออกเป็นแบบเดิมก่อน

2024-12-24 15:04 UTC, monshinawatra commented on lib/component/navbar.dart
> +                ? const Color.fromARGB(255, 18, 112, 194) // สีเมื่อเลือก
อันนี้อยากให้ทำเป็น variable ดีกว่าแบบ activeColor เป็นสีไง แบบไม่ active สียังไง

2024-12-24 15:09 UTC, monshinawatra commented on lib/component/navbar.dart
> +  BottomNavigationBarItem _buildNavItem({
น่าจะมีชื่อที่ดีกว่า _buildNavItem นะลองหาๆดูว่าเขาชอบใช้อะไรกัน

2024-12-24 15:18 UTC, monshinawatra commented on lib/page/Homepage.dart
> +      bottomNavigationBar: Navbar(),
ไม่แน่ใจว่าเราสามารถเอา Navbar ไปไว้ใน main.dart ได้รึป่าวมันจะได้ไม่ได้ สร้าง component ใหม่เรื่อยๆ ฝากลองหาๆหน่อย

2024-12-24 15:20 UTC, monshinawatra commented on lib/page/Homepage.dart
ยังสแกนดูไม่หมดฝากคลีนเพิ่มหน่อย ยังงงๆชื่อตัวแปร คิดว่ามันน่าจะดีได้มากกว่านี้คัช

2024-12-24 15:23 UTC, monshinawatra requested changes
- ลองเคลียพวกที่ comment ไป
- ไฟล์ฺไหนที่ไม่ได้ comment แต่มันมีปัญหาคล้ายๆกับที่ comment ฝากแก้ด้วย
- พวกสีอยากให้ใช้เป็นตัวแปรมากกว่าเพราะเราอาจจะได้เปลี่ยนสีธีมมันจะได้แก้ง่ายๆ

2024-12-29 11:56 UTC, Endo-Sym commented
เปลี่ยนสีจากที่สีrglb เป็น variable โดยทำเป็น componentขึ้นมา ชื่อว่า colors
เเก้ชื่อฟังก์ชันเเละตัวเเปรในหน้า Navbar Mygames ทำหน้าใส่fileเพื่อสรุป(ทำไปเเบคร่าว)
ไปหาวิธีใส่navbar ลงในmain.dart ยังไม่เจอ

2024-12-29 12:06 UTC, monshinawatra commented on lib/page/Homepage.dart
> +      bottomNavigationBar: Navbar(),
เดี๋ยวเก็บไว้เป็น Task หน้า

2024-12-29 12:12 UTC, monshinawatra approved these changes
Ok ครับ

2024-12-29 12:12 UTC, merged