Creategame
BetterACS/brainboost pull request #7
Opened 2024-12-31 12:50 UTC by Gxamsrtt023

2025-01-04 11:34 UTC, Endo-Sym reviewed
อยากให้เคลียcomment บางอันออก

2025-01-04 11:34 UTC, Endo-Sym commented on lib/creategame.dart
> +            label: 'Profile',
ตรงนี้น่าเป็นอันเก่า ใช้component ที่มีไว้เเล้วจะดีกว่า

2025-01-04 11:37 UTC, Endo-Sym requested changes
uploade ทำเป็นปุ่มใหม่น่าจะดีกว่า

2025-01-04 11:39 UTC, Endo-Sym approved these changes

2025-01-04 13:59 UTC, monshinawatra commented
![image](https://github.com/user-attachments/assets/ecbc043c-d593-47da-998f-d8d24ada020d)
แอบรู้สึกว่า commit เยอะเกินไป แล้วก็ชื่อแต่ละ commit มันไม่ค่อยสื่อความหมายเท่าไหร่ว่าทำอะไรไป ฝากครั้งหน้าแก้ไขให้ด้วยนะ
@Gxamsrtt023

2025-01-05 10:40 UTC, Endo-Sym reviewed
Code โอเคครับ เเต่ตรงnavbar import มา เเต่ไม่ได้ใช้งาน

2025-01-05 11:58 UTC, Endo-Sym approved these changes
Code โอเคเลยครับ เหลือทำให้เหมือนขึ้นครับ

2025-01-05 12:13 UTC, monshinawatra commented on lib/page/Gamescreen.dart
ฝากแก้พวกที่เป็นสีเอาไปใส่ใน `component/colors` แล้วเอามาใช้ในไฟล์นี้ให้หน่อย  แล้วใช้ `AppColor.สีเอา`

2025-01-05 12:15 UTC, monshinawatra commented on lib/page/Gamescreen.dart
> +class DottedCircle extends StatelessWidget {
อันนี้ปุ่ม Upload ปะ ฝากแก้ชื่อใหม่หน่อย เป็น `UploadCircleButton` ก็ได้ไม่ก็ชื่ออื่น

2025-01-05 12:17 UTC, monshinawatra commented on lib/page/Gamescreen.dart
> +class UploadFileScreen extends StatelessWidget {
ฝากเพิ่ม Comment แต่ละส่วนหน่อยว่าคือส่วนไหนๆ เช่น ส่วนหัว, ปุ่มอัพโหลด, พื้นหลัง ไรงี้

2025-01-05 12:17 UTC, monshinawatra requested changes
ฝากแก้หน่อยครับ ยังไม่อยาก merge เข้าไป

2025-01-08 09:52 UTC, monshinawatra commented on lib/creategame.dart
> +            label: 'Profile',
@Endo-Sym  อันนี้ ล่าสุดแก้แล้วใช่ไหมนะ

2025-01-11 12:23 UTC, monshinawatra approved these changes

2025-01-11 12:38 UTC, merged